settings:
  variables:
    entity_tablet: sensor.sm_t550_screen_brightness
    entity_browser_mod: media_player.6df20891_ef535c5e
    translate_unknown: Unknown
    translate_idle: Inattivo
    translate_home: casa
    translate_not_home: fuori
    translate_available: Available
    translate_no_updates: No updates
    translate_update_available: Update available
    translate_updates_available: Updates available
